### ISSUE TITLE
[OVERVIEW] Follow-up issues from particle-particle interaction

### ISSUE THREAD

**Issue by CKehl** [OceanParcels/parcels#1063]
Please process / integrate this list of follow-up issues of particle-particle interaction in-order.

1. [x] Fix smalldt - longruntime issue (#1055 )
2. [ ] Handle State, Operation and Error codes in InteractionKernels (#1056 )
3. [x] ~~Implement InteractionKernels for JIT on SoA (#1057 )~~
4. [x] ~~Implement InteractionKernels for JIT and SciPy on AoS (#1058 )~~
5. [x] ~~Implement InteractionKernels for JIT and SciPy on Nodes (#1059 )~~
6. [x] ~~Implement MPI support for InteractionKernels (#1060 )~~
7. [ ] Expand tests to cases for interaction kernels (#1061  ) 
8. [ ] Jupyter notebook examples for InteractionKernel (#1062  )
