### ISSUE TITLE
Documentation revamp

### ISSUE THREAD

**Issue by VeckoTheGecko** [OceanParcels/parcels#1324]
I'll use this issue to outline the ideas I have for the documentation, so that discussion can be centralised here with PRs linking back to this. Any of these points are up for discussion. I'm happy to work on all of these (although may need some additional help with config). If anyone else would like to contribute to a bulletpoint, drop a comment 🙂 (although there's no expectation on my end).

As these changes get implemented, I will edit this description adding the PR numbers to the bullet points.

# Changes
## Major changes
- [x] Documentation restructure
  - Add sectioning to the documentation, breaking apart the documentation into its conceptual components so that it isn't one large page.
- [x] Migrate to PyData theme (#1321)
  - The PyData theme is a much cleaner theme, with more features.
- [x] Create contribution guidelines for `parcels`
  - Having guidelines that contributors can follow would be good to communicate the standards adopted by the codebase.
  - The contributing [guidelines from geopandas](https://geopandas.org/en/stable/community/contributing.html) might be good to copy and slightly adapt to our purposes (ie. we only support Python 3.8+ (@erikvansebille it would be good to confirm this, I'm going off the `environment_*.yml` files), we don't use `black`, and [commit message conventions](https://geopandas.org/en/stable/community/contributing.html#commit-message-conventions) might be a bit extra for the size of this project).
  - The contribution guidelines can be its own page on the documentation website.
  - Perhaps [oceanparcels.org](https://oceanparcels.org) can be updated to link to the contributing page for dev installs.
- [x] Use [`flake8-docstrings`](https://pypi.org/project/flake8-docstrings/) to monitor docstring quality (#1321)
- [x] Migrate docstring format to the [Numpy Docstring Standard](https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard)
  - The `rst` format is quite difficult to read when displayed in IDEs.
  - Due to this ^, the Numpy Docstring Standard has been adopted by many other scientific packages (numpy, pandas, geopandas, xarray, to name a few).
  - Existing docstrings can be easily converted from `rst` format into Numpy format using [`pyment`](https://pypi.org/project/pyment/).
  - Compiling and [validation](https://numpydoc.readthedocs.io/en/latest/validation.html) of Numpy docstrings is possible in the build process through Sphinx with the `numpydoc` package. This validation is in extension to `flake8-docstrings`, making sure that the docstring is in the Numpy standard format.
  - The validation step is particularly important to make sure breaking documentation changes fail CI/CD on pull requests, allowing them to be changed before being merged into main (the ReadTheDocs integration feature just below will greatly help with viewing documentation changes, and failing builds that break validation rules).
- [x] ReadTheDocs build on pull requests
  - ReadTheDocs can [build on pull requests, and report build status back to GitHub](https://docs.readthedocs.io/en/stable/pull-requests.html#features). This can be [set up in the ReadTheDocs panel](https://docs.readthedocs.io/en/stable/guides/pull-requests.html) (@erikvansebille your help here would be great).
- [ ] Type annotations and static typechecking
  - Having type annotations will greatly help with documentation, and reduce ambiguity amongst users on the types of different parameters.
  - Using `mypy` to do static typechecking will validate type annotations, making sure internally `parcels` is correctly typed.
- [ ] Improve support for documentation notebooks
  - Automatically link functions/classes to example notebooks in which they are called.
  - Generally increase the visibility of the example notebooks (eg. perhaps creating a gallery; although [oceanparcels.org](https://oceanparcels.org) does a good job of that already).
  - Still need to explore the viability of this feature, and how it will be implemented 🤔

## Minor changes
- [x] Have "view source" links in documentation link directly back to GitHub (#1321)
- [x] Disable search engine indexing of old documentation

## Bugfixes
- [x] ReadTheDocs + Pydata theme compatability
  - Currently on [my ReadTheDocs (`docs` branch)](https://veckoparcels.readthedocs.io/en/docs/) the PyData theme makes the dropdown (to switch between the different versions) completely disappear.

# Notes
PRs will be made into the `new_docs` branch to act as a staging area before they are rolled out to the community. Once this issue is completed, we'll merge `new_docs` to `master`.

---
The type annotation and docstring specific changes will mainly be applied to the following modules which are currently part of the documentation website as defined in the `.. automodule::` calls in `docs/index.rst`:

- `parcels.particleset.particlesetsoa`
- `parcels.fieldset`
- `parcels.field`
- `parcels.gridset`
- `parcels.grid`
- `parcels.particle`
- `parcels.application_kernels.advection`
- `parcels.application_kernels.advectiondiffusion`
- `parcels.application_kernels.EOSseawaterproperties`
- `parcels.application_kernels.TEOSseawaterdensity`
- `parcels.compilation`
- `parcels.interaction`
- `parcels.interaction.neighborsearch`
- `parcels.kernel.basekernel`
- `parcels.kernel.kernelaos`
- `parcels.kernel.kernelsoa`
- `parcels.particlefile.baseparticlefile`
- `parcels.particlefile.particlefileaos`
- `parcels.particlefile.particlefilesoa`
- `parcels.rng`
- `parcels.particleset.baseparticleset`
- `parcels.particleset.particlesetaos`
- `parcels.tools.statuscodes`
- `parcels.tools.converters`
- `parcels.tools.loggers`
- `parcels.plotting`
- `parcels.scripts.plottrajectoriesfile`
- `parcels.scripts.get_examples`
